const ADD_ELEMENT = 'ADD_ELEMENT';
const CHANGE_ELEMENT_MENU = 'CHANGE_MENU';
const DELETE_ELEMENT = 'DELETE_ELEMENT';
const TOGGLE_ELEMENT_MENU = 'TOGGLE_MENU';

export {
  ADD_ELEMENT,
  CHANGE_ELEMENT_MENU,
  DELETE_ELEMENT,
  TOGGLE_ELEMENT_MENU,
};
