const ADD_ELEMENT = 'ADD_ELEMENT';
const CHANGE_MENU = 'CHANGE_MENU';
const DELETE_ELEMENT = 'DELETE_ELEMENT';
const TOGGLE_MENU = 'TOGGLE_MENU';

export {
  ADD_ELEMENT,
  DELETE_ELEMENT,
  CHANGE_MENU,
  TOGGLE_MENU,
};
